spring:
  datasource:
    url: jdbc:postgresql://ep-twilight-lake-achyn9dw-pooler.sa-east-1.aws.neon.tech/mivotodb?sslmode=require&channel_binding=require
    username: mivoto
    password: npg_hQDZiyP04RtS
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: WARN
    pe.com.mivoto.service: DEBUG
