spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mivoto_dev}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG
    pe.com.mivoto.service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
